services:
  frontend:
    image: shreyastalole/shopping-list:latest
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: shreyastalole/quarkus-backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_URL=jdbc:postgresql://database:5432/product_db
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
